/**
 * Default preset registry loader. Owner: stage 2 (integration). Stage-1 preset owners do not edit this file.
 * Loads every preset file, validates each spec, checks aliases, and returns per-file counts.
 */

import { PatternRegistry } from '../core/registry.js';
import { PRESETS as t3_1 } from './t3_1.js';
import { PRESETS as t3_2 } from './t3_2.js';
import { PRESETS as t3_3 } from './t3_3.js';
import { PRESETS as t3_4 } from './t3_4.js';
import { PRESETS as t3_5 } from './t3_5.js';
import { PRESETS as t3_6 } from './t3_6.js';
import { PRESETS as t3_7 } from './t3_7.js';
import { PRESETS as t3_8 } from './t3_8.js';
import { PRESETS as t3_9 } from './t3_9.js';
import { PRESETS as t4_1 } from './t4_1.js';
import { PRESETS as t4_2 } from './t4_2.js';
import { PRESETS as t4_3 } from './t4_3.js';
import { PRESETS as t5 } from './t5.js';

export const PRESET_FILES = Object.freeze({
  'presets/t3_1.js': t3_1, 'presets/t3_2.js': t3_2, 'presets/t3_3.js': t3_3, 'presets/t3_4.js': t3_4,
  'presets/t3_5.js': t3_5, 'presets/t3_6.js': t3_6, 'presets/t3_7.js': t3_7, 'presets/t3_8.js': t3_8, 'presets/t3_9.js': t3_9,
  'presets/t4_1.js': t4_1, 'presets/t4_2.js': t4_2, 'presets/t4_3.js': t4_3, 'presets/t5.js': t5,
});

/**
 * Build a registry from all preset files. Throws if any spec fails (strict) or an alias is dangling.
 * @returns {{registry: PatternRegistry, report: {files: Record<string, {processed:number, skipped:number, failed:number}>, total:{processed:number, skipped:number, failed:number}, aliases:{processed:number, skipped:number, failed:number}}}}
 */
export function loadDefaultRegistry() {
  const registry = new PatternRegistry();
  const files = {};
  const total = { processed: 0, skipped: 0, failed: 0 };
  for (const [file, list] of Object.entries(PRESET_FILES)) {
    const r = registry.addAll(list, file);
    files[file] = { processed: r.processed, skipped: r.skipped, failed: r.failed };
    total.processed += r.processed;
    total.skipped += r.skipped;
    total.failed += r.failed;
  }
  const fin = registry.finalize();
  if (fin.failed > 0) {
    throw new Error(`preset aliases: ${fin.failed} failed\n${fin.errors.map((e) => `  ${e.id}: ${e.message}`).join('\n')}`);
  }
  return { registry, report: { files, total, aliases: { processed: fin.processed, skipped: fin.skipped, failed: fin.failed } } };
}
